"""create ai_tasks table

Revision ID: 39c009d9a9e3
Revises: 797388a7bcb8
Create Date: 2026-08-31 20:41:28.380939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c009d9a9e3'
down_revision = '797388a7bcb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('task_type', sa.Enum('voice_transcription', 'summary', 'additional_work_suggestion', 'qa_query', name='ck_ai_tasks_task_type', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'failed', name='ck_ai_tasks_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('input_ref', sa.String(), nullable=False),
    sa.Column('output', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tasks_job_id'), 'ai_tasks', ['job_id'], unique=False)
    op.create_index(op.f('ix_ai_tasks_organization_id'), 'ai_tasks', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tasks_organization_id'), table_name='ai_tasks')
    op.drop_index(op.f('ix_ai_tasks_job_id'), table_name='ai_tasks')
    op.drop_table('ai_tasks')
    # ### end Alembic commands ###