"""create payments table

Revision ID: 4ee1afb7c86b
Revises: e4c3ca554e88
Create Date: 2026-08-31 16:52:44.401922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee1afb7c86b'
down_revision = 'e4c3ca554e88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('method', sa.Enum('cash', 'card', 'bank_transfer', 'other', name='ck_payments_method', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('unpaid', 'paid', name='ck_payments_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_job_id'), 'payments', ['job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_job_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###