"""create organizations and users tables

Revision ID: c3671a08ddf0
Revises: 70bbf553e3d7
Create Date: 2026-08-03 14:46:06.396423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3671a08ddf0'
down_revision = '70bbf553e3d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###