"""create additional_work_items table

Revision ID: e4c3ca554e88
Revises: 85466df32f26
Create Date: 2026-08-31 16:47:33.810854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c3ca554e88'
down_revision = '85466df32f26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_work_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'billed', name='ck_additional_work_items_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_additional_work_items_job_id'), 'additional_work_items', ['job_id'], unique=False)
    op.create_index(op.f('ix_additional_work_items_organization_id'), 'additional_work_items', ['organization_id'], unique=False)
    op.create_index('ix_additional_work_items_organization_id_status', 'additional_work_items', ['organization_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_additional_work_items_organization_id_status', table_name='additional_work_items')
    op.drop_index(op.f('ix_additional_work_items_organization_id'), table_name='additional_work_items')
    op.drop_index(op.f('ix_additional_work_items_job_id'), table_name='additional_work_items')
    op.drop_table('additional_work_items')
    # ### end Alembic commands ###