"""create documents table

Revision ID: 797388a7bcb8
Revises: 4ee1afb7c86b
Create Date: 2026-08-31 17:02:10.043338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797388a7bcb8'
down_revision = '4ee1afb7c86b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('job_report', 'repair_certificate', name='ck_documents_type', native_enum=False, create_constraint=True, length=30), nullable=False),
    sa.Column('s3_key', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_job_id'), 'documents', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_job_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###