"""create jobs table

Revision ID: c972ee2d6d72
Revises: 3c5324a39f40
Create Date: 2026-08-31 16:12:39.952654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c972ee2d6d72'
down_revision = '3c5324a39f40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_technician_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('new', 'assigned', 'en_route', 'in_progress', 'awaiting_parts', 'awaiting_approval', 'completed', 'cancelled', name='ck_jobs_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('reported_issue', sa.String(), nullable=False),
    sa.Column('address_snapshot', sa.String(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_warranty_claim', sa.Boolean(), nullable=False),
    sa.Column('origin_job_id', sa.Uuid(), nullable=True),
    sa.Column('warranty_expires_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_technician_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_assigned_technician_id'), 'jobs', ['assigned_technician_id'], unique=False)
    op.create_index(op.f('ix_jobs_customer_id'), 'jobs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_jobs_equipment_id'), 'jobs', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index('ix_jobs_organization_id_assigned_technician_id', 'jobs', ['organization_id', 'assigned_technician_id'], unique=False)
    op.create_index('ix_jobs_organization_id_status', 'jobs', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_scheduled_at'), 'jobs', ['scheduled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_scheduled_at'), table_name='jobs')
    op.drop_index('ix_jobs_organization_id_status', table_name='jobs')
    op.drop_index('ix_jobs_organization_id_assigned_technician_id', table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_equipment_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_customer_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_assigned_technician_id'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###