"""add phone and avatar to users

Revision ID: ded664147cca
Revises: 39c009d9a9e3
Create Date: 2026-09-05 17:53:03.757511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded664147cca'
down_revision = '39c009d9a9e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('avatar_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_s3_key')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###