"""create job_status_history table

Revision ID: df32a573a2e6
Revises: c972ee2d6d72
Create Date: 2026-08-31 16:21:28.710884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df32a573a2e6'
down_revision = 'c972ee2d6d72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_status_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('from_status', sa.Enum('new', 'assigned', 'en_route', 'in_progress', 'awaiting_parts', 'awaiting_approval', 'completed', 'cancelled', name='ck_job_status_history_from_status', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('to_status', sa.Enum('new', 'assigned', 'en_route', 'in_progress', 'awaiting_parts', 'awaiting_approval', 'completed', 'cancelled', name='ck_job_status_history_to_status', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_status_history_job_id'), 'job_status_history', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_status_history_job_id'), table_name='job_status_history')
    op.drop_table('job_status_history')
    # ### end Alembic commands ###